test:
  image: node:latest
  script:
    - yarn install
    - node test-utils/wait-for-ports.js selenium 2222 24444
    - DEBUG="child-service:*" SELENIUM_HOST=selenium START_STORYBOOK=true yarn test
  artifacts:
    name: snapshots
    paths:
      - __image_snapshots__
    when: on_failure
  services:
    - name: "knappmeier/selenium-with-tunnel"
      alias: selenium
